#ifndef DMC_CONSTANTS_H
#define DMC_CONSTANTS_H

const int DMC_SERVER_CONNECTION_UPLOAD_COMPLETE = 0;
const int DMC_SERVER_CONNECTION_UPLOAD_NOT_STARTED = -1;
const int DMC_SERVER_CONNECTION_CONTROLLER_UPLOAD_ERROR = -2;

#endif // DMC_CONSTANTS_H
