name: DMHelper CI Windows Workflow

on:
  workflow_dispatch:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        cache: 'true'
        modules: 'qtcharts qtwebengine'
    - uses: actions/checkout@v3
    - name: Print current working dir
      run: |
        pwd
        echo Location of github.workspace:
        echo ${{ github.workspace }}
        ls DMHelper
        cd DMHelper
        pwd
        echo ${{env.PATH}}
    - name: Set the Qt Version environment variable
      uses: myci-actions/export-env-var-powershell@1
      with:
        name: QT_VERSION
        value: 6.6.0
    - name: Set the Qt Installer Version environment variable
      uses: myci-actions/export-env-var-powershell@1
      with:
        name: QT_INSTALLER_VERSION
        value: 4.6
    - name: Set the MSVC Version environment variable
      uses: myci-actions/export-env-var-powershell@1
      with:
        name: MSVC_VERSION
        value: 2019
    - name: Append the directory of 'vcvarsall.bat' to PATH environment variable
      uses: myci-actions/export-env-var-powershell@1
      with:
        name: PATH
        value: ${{env.QT_DIR}}\${{env.QT_VERSION}}\msvc${{env.MSVC_VERSION}}_64\bin;${{env.QT_DIR}}\Tools\QtInstallerFramework\${{env.QT_INSTALLER_VERSION}}\bin;${{env.QT_DIR}}\Tools\QtCreator\bin;${{env.QT_DIR}}\Tools\QtCreator\bin\jom;C:\Program Files (x86)\Microsoft Visual Studio\${{env.MSVC_VERSION}}\Enterprise\VC\Auxiliary\Build;$env:PATH
    - name: Set up environment for build
      run: |
        echo ${{env.PATH}}
        pwd
        cd DMHelper
        mkdir bin64
        mkdir bin64\config
        mkdir bin64\packages
        mkdir bin64\packages\com.dmhelper.app
        mkdir bin64\packages\com.dmhelper.app\meta
        mkdir bin64\packages\com.dmhelper.app\data
        mkdir bin64\packages\com.dmhelper.app\data\bestiary
        mkdir bin64\packages\com.dmhelper.app\data\doc
        mkdir bin64\packages\com.dmhelper.app\data\pkgconfig
        mkdir bin64\packages\com.dmhelper.app\data\plugins
        mkdir bin64\packages\com.dmhelper.app\data\resources
        mkdir bin64\packages\com.dmhelper.app\data\resources\tables
        xcopy /s src\installer\* bin64\*
        mv bin64\packages\com.dmhelper.app\meta\installscript64.qs installscript.qs
        pwd
    - name: Build DMHelper for Windows
      run: |
        pwd
        cd DMHelper
        mkdir build-64_bit-release
        cd build-64_bit-release
        call vcvarsall.bat x64
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake.exe ..\src\DMHelper.pro -spec win32-msvc "CONFIG+=qtquickcompiler" 
        jom.exe /d /f Makefile qmake_all
        jom.exe /d /f Makefile.Release
        ls
