name: DMHelper CI Linux Workflow

on:
  workflow_dispatch:

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION: 6.6.0
  QT_INSTALLER_VERSION: 4.7
  # MSVC_VERSION: 2019
  # INSTALLERARTIFACT: DMHelper-64-bit-release-Installer.exe
  # ZIPARTIFACT: DMHelper-64-bit-release.zip

jobs:
  build-DMH-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.6.0'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtimageformats qtmultimedia qtnetworkauth'
        tools: 'tools_ifw'
        archives: 'qttranslations qttools qtsvg qtbase'
        
    - name: Check out the DMHelper source tree
      uses: actions/checkout@v3
    
    - name: Print current working dir
      run: |
        echo Workspace is: ${{ github.workspace }}
        ls DMHelper
        cd DMHelper
        pwd
        echo 'runner.workspace === ${{ runner.workspace }}'
        echo 'github.workspace === ${{ github.workspace }}'
        ls ${{env.Qt6Dir}}
        tree
        # Get-ChildItem -Recurse -Directory
        # echo ${{ runner.workspace }}\Qt\Tools\QtInstallerFramework\${{ env.QT_INSTALLER_VERSION }}\bin\binarycreator
        # cd ${{ runner.workspace }}\Qt\Tools\QtInstallerFramework\${{ env.QT_INSTALLER_VERSION }}\bin
        # Get-ChildItem -Recurse -Directory
        # echo STOP!
        # Dosomethingthatbreaks
        
    - name: Build DMHelper for Linux
      run: |
        cd DMHelper
        mkdir build-64_bit-release
        cd build-64_bit-release
        qmake.exe ..\src\DMHelper.pro -spec linux-g++-64 "CONFIG+=qtquickcompiler" 
        # ${{ runner.temp }}\jom\jom.exe /d /f Makefile qmake_all
        # ${{ runner.temp }}\jom\jom.exe /d /f Makefile.Release
        make
        
    - name: Zip the build
      run:  |
        cd DMHelper
        7z a -tzip DMHelper-linux-64-bit-release.zip .\bin64\packages\com.dmhelper.app\data\*
    
    - name: Output the workspace directory tree contents
      run: |
        # Get-ChildItem -Recurse
        tree

    - name: Save the zip file
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.ZIPARTIFACT }}
        path: ${{ github.workspace }}\DMHelper\${{ env.ZIPARTIFACT }}
