name: DMHelper CI MacOS Workflow

on:
  workflow_dispatch:

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION: 6.6.0
  QT_INSTALLER_VERSION: 4.6
  INSTALLERARTIFACT: DM-Helper-macOS-release-Installer.zip
  ZIPARTIFACT: DMHelper-macOS-release.zip

jobs:
  build-DMH-macos:

    runs-on: macos-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.6.0'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        cache: 'true'
        modules: 'qtmultimedia qtnetworkauth qtimageformats'
        tools: 'tools_ifw'
        add-tools-to-path: 'true'
        archives: 'qttranslations qttools qtsvg qtbase opengl32sw d3dcompiler_47'
        
    - name: Check out the DMHelper source tree
      uses: actions/checkout@v3
    
    - name: Print current working dir
      run: |
        cd DMHelper
        echo Workspace is: ${{ github.workspace }}
        echo 'runner.workspace === ${{ runner.workspace }}'
        echo 'github.workspace === ${{ github.workspace }}'
        echo 'Qt6Dir === ${{env.Qt6_DIR}}'
        
    - name: Set up environment for build
      run: |
        echo "Current environmental path: ${{env.PATH}}"
        cd DMHelper
        mkdir -p {build-clang_64bit-Release,bin64/config,bin64/packages/com.dmhelper.app/{meta,data}}
        cp -R src/installer/ bin64/
        mv bin64/packages/com.dmhelper.app/meta/installscript64.qs bin64/packages/com.dmhelper.app/meta/installscript.qs
        ls -alR

    - name: Build DMHelper for MacOS
      run: |
        cd DMHelper
        cd build-clang_64bit-Release
        ${{env.Qt6_DIR}}/bin/qmake ../src/DMHelper.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler
        make -j4

    - name: Copy binary resources
      run: |
        cd DMHelper
        cd build-clang_64bit-Release
        cp -R DMHelper.app/ ../bin64/packages/com.dmhelper.app/data/DMHelper.app/
        cp ../src/bin-macos/Info.plist ../bin64/packages/com.dmhelper.app/data/DMHelper.app/Contents/
        mkdir ../bin64/packages/com.dmhelper.app/data/DMHelper.app/Contents/Frameworks/pkgconfig
        cp ../src/bin-macos/pkgconfig/* ../bin64/packages/com.dmhelper.app/data/DMHelper.app/Contents/Frameworks/pkgconfig
        mkdir ../bin64/packages/com.dmhelper.app/data/DMHelper.app/Contents/Frameworks/plugins
        cp -R ../src/bin-macos/vlc/plugins/* ../bin64/packages/com.dmhelper.app/data/DMHelper.app/Contents/Frameworks/plugins

    - name: Call Deploy for Qt
      run: |
        cd DMHelper
        cd bin64/packages/com.dmhelper.app/data
        otool -L DMHelper.app/Contents/MacOS/DMHelper
        cd ../../../../
        ${{env.Qt6_DIR}}/bin/macdeployqt ./bin64/packages/com.dmhelper.app/data/DMHelper.app/
        cp -R ./src/bestiary/ ./src/resources/ ./src/doc/ ./src/bin-macos/DMHelper.icns ./bin64/packages/com.dmhelper.app/data/DMHelper.app/Contents/Resources

    - name: Create the installer
      run: |
        cd DMHelper
        cd bin64
        ${{ runner.workspace }}/Qt/Tools/QtInstallerFramework/${{ env.QT_INSTALLER_VERSION }}/bin/binarycreator -c ./config/config_mac.xml -p ./packages "DM-Helper-macOS-release-Installer"
        zip -r ${{ env.INSTALLERARTIFACT }} ./DM-Helper-macOS-release-Installer.app
        mv ${{ env.INSTALLERARTIFACT }} ../
        
    - name: Zip the build
      run:  |
        cd DMHelper
        cd ./bin64/packages/com.dmhelper.app/data
        zip -r ${{ env.ZIPARTIFACT }} *
        mv ${{ env.ZIPARTIFACT }} ../../../../
    
    - name: Output the workspace directory tree contents
      run: |
        ls -alR

    - name: Save the zip file
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.ZIPARTIFACT }}
        path: ${{ github.workspace }}/DMHelper/${{ env.ZIPARTIFACT }}

    - name: Save the install file
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.INSTALLERARTIFACT }}
        path: ${{ github.workspace }}/DMHelper/${{ env.INSTALLERARTIFACT }}
